In [1]:
import numpy as np

In [2]:
A = np.array([[1, 1, 3], [3, 2, 1], [1, 0, 3]])
K = np.array([[1, 0, 3], [0, 2, 0], [1, 0, 3]])
print(A)
print(K)

A*K

[[1 1 3]
 [3 2 1]
 [1 0 3]]
[[1 0 3]
 [0 2 0]
 [1 0 3]]


array([[1, 0, 9],
       [0, 4, 0],
       [1, 0, 9]])

In [4]:
["2"] * 3

['2', '2', '2']